services:
  app:
    build:
      context: .
    container_name: blogs
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres-db:5432/postgres
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    command: ['npm', 'run', 'dev']

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
